MySQL:
  enabled: false
  host: 'localhost'
  database: 'db'
  username: 'user'
  password: 'pass'
  port: 3306

Settings:
  price:
    min: 100000
    max: 500000
  stack-radius: 5
  looting-bonus: 10000
  save-interval: 600 # em segundos
  spawner-update: 200 # em ticks
  tax-remove-stack: 10 # em porcentagem
  next-update: 0
  always-enabled-worlds:
    - 'RankupWorld'
  hologram:
    - '&6&lMOBSPAWNER'
    - ''
    - '&7Dono: &f{owner}'
    - '&7Tipo: &f{type}'
    - '&7Stack: &f{stack}'
    - '&7Drops: &f{drops}'
    - '&7Integridade: &f{integrity}'
    - '&7Energia: &f{energy}'
    - '&7Status: {status}'

Titles:
  when-kill:
    title: ''
    subtitle: '&a&l+{drops} ✸'
  when-sell:
    title: ''
    subtitle: '&e&l+{value} ⛃'

Messages:
  public: '&aPúblico'
  private: '&cPrivado'
  enabled: '&aLigado'
  disabled: '&cDesligado'
  'true': '&aSim'
  'false': '&cNão'
  zero-spawners-energy: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui spawners para energizar!'
  zero-spawners-repair: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui spawners para reparar!'
  successful-energized: '&6&lVoltz&f&lMC &8&l➜ &7Você energizou &f{spawners} &7spawners, totalizando &f{energy} Watts &7para cada!'
  successful-repaired: '&6&lVoltz&f&lMC &8&l➜ &7Você reparou &f{spawners} &7spawners, totalizando em média &f{repair}% &7para cada!'
  remove-stack-min: '&6&lVoltz&f&lMC &8&l➜ &cA quantia precisa ser acima de {tax}!'
  remove-stack-successful: '&6&lVoltz&f&lMC &8&l➜ &7Stacks removidos com sucesso! &f{lost} &7spawners foram destruídos nesse processo.'
  incorrect-pickaxe: '&6&lVoltz&f&lMC &8&l➜ &c{lost} spawners foram destruídos por não ter usado uma ferramenta ideal de remoção!'
  remove-stack:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Digite no chat quantos spawners deseja remover!'
    - '&6&lVoltz&f&lMC &8&l➜ &7Para remover todos, digite `&f*&7`'
    - '&6&lVoltz&f&lMC &8&l➜ &7Lembre-se que há uma taxa de &f{tax}% &7ao remover stacks!'
    - ''
  only-owner: '&6&lVoltz&f&lMC &8&l➜ &cApenas o dono pode gerenciar as permissões!'
  offline-player: '&6&lVoltz&f&lMC &8&l➜ &cEsse jogador está offline!'
  invalid-spawner: '&6&lVoltz&f&lMC &8&l➜ &cO spawner informado não existe!'
  invalid-amount: '&6&lVoltz&f&lMC &8&l➜ &cA quantia informada é inválida!'
  buy-all-zero: '&6&lVoltz&f&lMC &8&l➜ &cVocê não pode comprar nenhum spawner por falta de coins!'
  insufficient-money: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui coins suficientes!'
  spawner-usage: '&6&lVoltz&f&lMC &8&l➜ &cUso correto: /spawners give/fuel/pickaxe/repair <jogador> [spawner] <quantia>!'
  need-permission: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui permissão para fazer isso!'
  has-permission: '&6&lVoltz&f&lMC &8&l➜ &cEsse jogador já possui permissões nesse spawner!'
  spawner-permission: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui permissão para usar esse spawner!'
  near-spawner: '&6&lVoltz&f&lMC &8&l➜ &cHá um spawner próximo a esse local! Afaste-se e tente novamente.'
  choose-amount:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Digite no chat quantos spawners deseja comprar!'
    - ''
    - ' &8▶ &7Comprando: &f{spawner}'
    - ' &8▶ &7Preço: &e{price}'
    - ''
  successful-purchased:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Compra efetuada com sucesso!'
    - ''
    - ' &8▶ &7Item adquirido: &f{spawner}'
    - ' &8▶ &7Quantia: &fx{amount}'
    - ' &8▶ &7Preço: &e{price}'
    - ''
  wait: '&6&lVoltz&f&lMC &8&l➜ &aAdicionando amigo, aguarde...'
  new-quotation:
    - ''
    - '&6&l[Spawners] &7A cotação mudou! Verifique os novos valores de drops digitando &f/spawners&7!'
    - ''
  add-friend:
    - '&6&lVoltz&f&lMC &8&l➜ &7Digite no chat o nick do jogador!'

Energy:
  type: PLAYER_HEAD
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzc0MDBlYTE5ZGJkODRmNzVjMzlhZDY4MjNhYzRlZjc4NmYzOWY0OGZjNmY4NDYwMjM2NmFjMjliODM3NDIyIn19fQ==
  name: '&bEnergia &7[&f+{amount}&7]'
  lore:
    - '&7Use esse item para'
    - '&7energizar os spawners!'

Infinite-Energy:
  type: PLAYER_HEAD
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzFjODk1OTM1MTc0YWM1ZjY0ZWRhZDIxNWNlMGI2YjM4MDEzN2NjNGQxZjM5OWEzZGYxN2RjM2IyZGU0MGJkZSJ9fX0=
  name: '&bEnergia ∞'
  lore:
    - '&7Use esse item para'
    - '&7energizar os spawners!'
    - ''
    - '&7Essa energia é infinita!'

Pickaxe:
  type: DIAMOND_PICKAXE
  name: '&6Toque Suave ∞'
  glow: true
  lore:
    - '&7Use essa picareta para remover'
    - '&7spawners sem destruí-los!'

Repair:
  type: PLAYER_HEAD
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWVmNWFjZjEzNGZhOTUyZjEzZmRmMGIzODk5MDYwY2MxOGViYzBhOTcxMzQ3ZTQ1YTMxZWNmOTVhNGIwYjMxYyJ9fX0=
  name: '&6Reparador de Spawners &7[&f+{percentage}%&7]'
  lore:
    - '&7Use esse item para restaurar'
    - '&7a integridade de seus spawners!'

Infinite-Repair:
  type: PLAYER_HEAD
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmM0MTlhNDRjNWI5NjdmNDczMTZkMWJlZDNjYzYzMmJkZWQxOTlhNWMzNDIxMTc5MWM3MGY5OThmZGJkNiJ9fX0=
  name: '&6Reparador de Spawners ∞'
  lore:
    - '&7Use esse item para restaurar'
    - '&7a integridade de seus spawners!'
    - ''
    - '&7Esse reparador é infinito!'

Gift:
  type: PLAYER_HEAD
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjBmMjMxNmU0NTVhYzNjM2ZhMmUwZWQ1MmYzMDVjYzRiYzM2M2FiYWZmMTU1M2JiNzE3MGIwZGM4MzY4YWJjMSJ9fX0=
  name: '&6Presente'
  lore:
    - '&7Seja bem-vindo ao servidor!'
    - '&7Abra esse presente para ver'
    - '&7o que há dentro!'

Next-Page:
  type: ARROW
  name: '&aPróxima Página'

Previous-Page:
  type: ARROW
  name: '&cPágina Anterior'

Time-Formatter:
  second: segundo
  seconds: segundos
  minute: minuto
  minutes: minutos
  hour: hora
  hours: horas
  day: dia
  days: dias
  now: agora

Number-Formatter:
  - "k"
  - "M"
  - "B"
  - "T"
  - "Q"
  - "QQ"
  - "S"
  - "SS"
  - "O"
  - "N"
  - "D"