name: Spawners
description: Only a simple spawners plugin.
version: 1.0
api-version: 1.16
author: zPedroo_
main: com.zpedroo.voltzspawners.VoltzSpawners
depend: [WorldGuard, HolographicDisplays, Vault, ProtocolLib]
load: POSTWORLD
commands:
  spawners:
    aliases: [spawner, mobspawner, mobspawners]